# Generated by Django 3.0.5 on 2020-04-22 11:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0002_auto_20200422_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 22, 11, 45, 12, 411390, tzinfo=utc), null=True),
        ),
    ]
