# Generated by Django 3.0.5 on 2020-04-22 11:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0003_auto_20200422_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 22, 11, 55, 7, 467832, tzinfo=utc), null=True),
        ),
    ]
